### ISSUE TITLE
Create Pull Request Template and Pull Request Rules based on Node.js's ones

### ISSUE THREAD

**Issue by ovflowd** [nodejs/api-docs-tooling#13]
This issue is an administrative task, so we created a Pull Request Template and Repository Rules similar to the Node.js Website. The Node.js Website is shown below:

(Keep in mind since we have no deployment/GitHub Action yet, we don't have any specific Status Check)

#### List of Rules

![image](https://github.com/nodejs/api-docs-tooling/assets/12037269/a75bb14c-1d04-4f35-9aba-f28266c5f162)

#### 1st Rule

![image](https://github.com/nodejs/api-docs-tooling/assets/12037269/87602f08-ce6c-4ec4-b7c8-b1851172c0f7)

![image](https://github.com/nodejs/api-docs-tooling/assets/12037269/9697c49d-93f6-4f83-ad7e-069989eed022)

#### 2st Rule

![image](https://github.com/nodejs/api-docs-tooling/assets/12037269/f5f1553c-0173-4a99-8f41-4e7665fc4b85)

![image](https://github.com/nodejs/api-docs-tooling/assets/12037269/65dc8c8b-6dd8-4e54-bdd3-d5f1d73789cf)

![image](https://github.com/nodejs/api-docs-tooling/assets/12037269/771d2839-482e-4408-bcdc-333cc696ac85)

**Comment by AugustinMauroy** [comment]
I'm not the best person for this kind of administrative question, but I think we should just allow squash and merge like on nodejs.org.

**Comment by flakey5** [comment]
Protection rules created

**Comment by flakey5** [comment]
Pull request rules created minus the status checks.

For both rules I just copied 1:1 what was in the screenshots above.

**Comment by AugustinMauroy** [comment]
"realeaser" are on rules set for pr. I don't think it's necessary because the team has no interest here.

**Comment by flakey5** [comment]
> "realeaser" are on rules set for pr. I don't think it's necessary because the team has no interest here.

Updated to remove the `releasers` from the pr rules
