### ISSUE TITLE
Setup test environment

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/api-docs-tooling#19]
Setting up a test environment would allow each function to be tested individually in order to ensure stability throughout the project.

To do this, I suggest using [vitest](https://vitest.dev), which is faster and more stable than [jest](https://jestjs.io). And it wraps the environment for Preact.

Should we use nodejs test-runner? Honestly, I think not, because if we have to test web components with tailwind and css module and typescript, it gets really complicated with nodejs test-runner.

We'll also need to set up GitHub actions to retrieve the test coverage.

**Comment by AugustinMauroy** [comment]
@ovflowd can I have your opinion ?

**Comment by ovflowd** [comment]
I need clarification ont this yet. After we accomplish the initial migration parts, we can add unit testing. But should we also have end-to-end testing? Like a sample doc, we grab from node/node to test against? :thinking: 

I think it'd make sense to compile a list of what we want to test

**Comment by AugustinMauroy** [comment]
For me we need these test:
- unit test for the parse, to unsure it's parse as expect. _it would tend towards a spec_
- unit test if we have preact component here
- Test run by hand or trigger on GitHub action which fetches the docs on node core main branch to test everything. So kind E2E testing

**Comment by flakey5** [comment]
I'm +1 on adding the tests when we need them (i.e. in the same pr for #2 or one after). Before then I don't really see how it'd help

**Comment by ovflowd** [comment]
Feel free to add tests!
