### ISSUE TITLE
Add a CLI mode to the parser (`cli.mjs`)

### ISSUE THREAD

**Issue by ovflowd** [nodejs/api-docs-tooling#3]
After completing #1, we aim to add a "JavaScript binary" that you can quickly call, following NPM's `package.json` documentation for [`bin`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#bin).

This aims to provide functionality to:

- Provide a `glob` for input (`-i`)
  - This can be a single API doc file, or a glob to all markdown files of a folder or subfolder (like `doc/api/*.md`
- Provide an output folder path `-o`
  - This is not a glob but simple a directory to output generated contents
  - File names will match input file names
- Provide an execution target mode (`-t`)
  - Initially it will only support `mdx` this can be a comma-separated value of one or more output formats we'll support in the future (like `json`, `html`, `mdx`)

This file should be stored within a `bin/cli.mjs` file

**Comment by ovflowd** [comment]
cc @canerakdas I remember you were looking for options here?

**Comment by canerakdas** [comment]
> cc @canerakdas I remember you were looking for options here?

Yes, I'm working on it 🚀
