### ISSUE TITLE
Add basic ESLint setup (For ESM) and Prettier

### ISSUE THREAD

**Issue by ovflowd** [nodejs/api-docs-tooling#4]
We should add a basic ESLint configuration (it can be based on https://github.com/nodejs/nodejs.org/blob/main/.eslintrc.json), except that it should only contain the rules for vanilla JavaScript (ESM) and nothing else (like Jest o React or TypeScript, etc...)

Same for Prettier, we should also add a Prettier configuration; we can also base it on the Node.js's Website ones (feel free to also grab the `.editorconfig`, and other base files).

We don't need Markdown or MDX linting/prettier rules as this repository itself won't hold any Markdown/MDX file.

**Comment by araujogui** [comment]
working on this

**Comment by cclauss** [comment]
Do you folks use https://pre-commit.com so that lint-level tests can be run locally as part of the git commit process as well as in GitHub Actions?

**Comment by AugustinMauroy** [comment]
on `node/nodejs.org` we use husky to handle that I think we can do same here
